version: '{build}'
branches:
  only:
    - master
image:
  - Visual Studio 2017
environment:
  matrix:
    - generator: Visual Studio 15 2017
      cf: -DBUILD_SHARED_LIBS=OFF -T v141_xp
    - generator: Visual Studio 15 2017
      cf: -DBUILD_SHARED_LIBS=ON
    - generator: Visual Studio 15 2017 Win64
      cf: -DBUILD_SHARED_LIBS=OFF
    - generator: Visual Studio 15 2017 Win64
      cf: -DBUILD_SHARED_LIBS=ON
install:
  - cmd: git clone https://github.com/huskyproject/huskylib  C:\projects\huskylib
  - cmd: git clone https://github.com/huskyproject/smapi  C:\projects\smapi
  - cmd: git clone https://github.com/huskyproject/fidoconf  C:\projects\fidoconf
build_script:
  - cmd: 
      cd C:\projects\huskylib && mkdir build && cd build && cmake --version &&  cmake .. -G "%GENERATOR%" %CF% && cmake --build . -- /P:Configuration=Release &&
      cd C:\projects\smapi && mkdir build && cd build && cmake --version &&  cmake .. -G "%GENERATOR%" %CF% && cmake --build . -- /P:Configuration=Release &&
      cd C:\projects\fidoconf && mkdir build && cd build && cmake --version &&  cmake .. -G "%GENERATOR%" %CF% && cmake --build . -- /P:Configuration=Release &&
      cd C:\projects\areafix && mkdir build && cd build && cmake --version &&  cmake .. -G "%GENERATOR%" %CF% && cmake --build . -- /P:Configuration=Release
